export { Infra as CreateInfraModal } from "./Create/Infra/Infra.component";
export { Laboratories as CreateLaboratoriesModal } from "./Create/Laboratories/Laboratories.component";
export { Locations as CreateLocationsModal } from "./Create/Locations/Locations.component";
export { Infra as UseInfraCrud } from "./Crud/Infra/infra.hook";
export { Laboratories as UseLaboratoriesCrud } from "./Crud/Laboratories/laboratories.hook";
export { Locations as UseLocationsCrud } from "./Crud/Locations/Locations.hook";
export { Infra as EditInfraModal } from "./Edit/Infra/Infra.component";
export { Laboratories as EditLaboratoriesModal } from "./Edit/Laboratories/Laboratories.component";
export { Locations as EditLocationsModal } from "./Edit/Locations/Locations.component";
